<?php
/**
* @file
* @Author       Michael Cuccaro
* @license      https://opensource.org/licenses/GPL-3.0
* A module to automatically subscribe new drupal users to an Enflyer memberlist.
*/

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function enflyer_drupal_auto_subscribe_help($path, $arg)
{
        switch($path)
        {
                case "admin/help#enflyer_drupal_auto_subscribe":
                        watchdog('enflyer_as', 'enflyer help called', $variables = array(), $severity = WATCHDOG_NOTICE, $link = NULL);
                        return '' . t("Auto subscribe new users to an Enflyer memberlist") . '';
                        break;
        }
}

/**
 * Implements hook_user_insert
*/
function enflyer_drupal_auto_subscribe_user_insert($edit, $account, $category)
{
        $url            = 'http://winflyer.emsvc.com/autoform_display.php';
        $autoform_id    = variable_get('enflyer_drupal_auto_subscribe_autoform_id', '');
        $autoform_key   = variable_get('enflyer_drupal_auto_subscribe_autoform_key', '');
        $email  = $account->mail;

	if( empty($autoform_id) )
	{
		myWatchDog('You must provide an autoform id'); return 0;		
	}

	if( empty($autoform_key) )
	{
		myWatchDog('you must provide an autoform key'); return 0;
	}

        $data_construct = array('action' => 'add', 'fields[autoform_id]' => $autoform_id, 'fields[af_key]' => $autoform_key, 'fields[email]' => $email);
        $encoded_data   = drupal_http_build_query($data_construct);

        //myWatchDog(print_r($account, true));
        $request_options        = array (
                'method'        => 'POST',
                'data'          => $encoded_data,
                'headers' => array('Content-Type' => 'application/x-www-form-urlencoded')
        );
        $response = drupal_http_request($url, $request_options);
	if( isset($response->error) )
	{
		myWatchDog('error: ' . $response->error);
	}
	else
	{
		myWatchDog('success! ');
	}
}

function _admin() {
  $form = array();

  return system_settings_form($form);
}

/**
 * Implements hook_menu().
 */
function enflyer_drupal_auto_subscribe_menu() {
  $items = array();

  $items['admin/config/content/enflyer_drupal_auto_subscribe'] = array(
    'title' => 'enflyer drupal auto subscribe',
    'description' => 'Configuration for enflyer drupal auto subscribe module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('enflyer_drupal_auto_subscribe_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: enflyer drupal auto subscribe settings
 *
 * @see enflyer_drupal_auto_subscribe_menu()
 */
function enflyer_drupal_auto_subscribe_form($form, &$form_state) {
  $form['enflyer_drupal_auto_subscribe_autoform_id'] = array(
    '#type' => 'textfield',
    '#title' => t('autoform id'),
    '#default_value' => variable_get('enflyer_drupal_auto_subscribe_autoform_id',''),
    '#size' => 16,
    '#maxlength' => 16,
    '#description' => t('The autoform (signup form) id.'),
    '#required' => TRUE,
  );
  $form['enflyer_drupal_auto_subscribe_autoform_key'] = array(
    '#type' => 'textfield',
    '#title' => t('autoform key'),
    '#default_value' => variable_get('enflyer_drupal_auto_subscribe_autoform_key',''),
    '#size' => 16,
    '#maxlength' => 16,
    '#description' => t('The autoform (signup form) key.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/*
* for faster logging
*/
function myWatchDog($arg_message)
{
        watchdog('enflyer_as', $arg_message, $variables = array(), $severity = WATCHDOG_NOTICE, $link = NULL);
}
